### ISSUE TITLE
Create API documentation for Space People (CRUD space members)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ribose-api#11]
@skalee , would you be able to help us document the Ribose API (which is implemented in https://github.com/riboseinc/ribose-ruby/) for the Space People section, in the Apiary MSON format?

You can find out the details of the API in the gem (and maybe some reverse engineering of our web interface), and @abunashir would also be able to help.

Let me know. Thanks!

**Comment by skalee** [comment]
@ronaldtse sure.

**Comment by skalee** [comment]
@ronaldtse Is there any piece of similar documentation for other API sections of this gem I should base on? Or do we start it from scratch?

**Comment by ribose-jeffreylau** [comment]
@skalee  @PeterTKY added the [**Calendar**](http://docs.ribose.apiary.io/reference/calendar) section, while I converted the [**Invitation**](https://github.com/riboseinc/ribose-api/wiki/Invitation-API) section from [the Github wiki](https://github.com/riboseinc/ribose-api/wiki) to the APIB format, which you can refer to when helping us convert the other sections.

We use the `Group` directive to group sections.

Build instructions for the APIB files can be found in [the README.adoc in this repo](https://github.com/riboseinc/ribose-api/blob/master/README.adoc).

**Comment by skalee** [comment]
@ribose-jeffreylau Thanks! I was looking for it in client's repo for some reason. Now it's all clear.

**Comment by ribose-jeffreylau** [comment]
@skalee 

I apologise that I have accidentally implemented this without realizing sooner!

Let me reassign this task to myself...  Sorry about that 😅

**Comment by ronaldtse** [comment]
Thank you @ribose-jeffreylau !

**Comment by skalee** [comment]
No problem @ribose-jeffreylau, I had little time earlier this week anyway!
