### ISSUE TITLE
Check blueprints well-formedness in CI

### ISSUE THREAD

**Issue by skalee** [riboseinc/ribose-api#33]
Run [Drafter](https://github.com/apiaryio/drafter-npm) in Travis CI environment to prove that API blueprints are well-formed. See https://github.com/riboseinc/ribose-api/issues/1#issuecomment-341796160 and subsequent comments for rationale and details.

**Comment by skalee** [comment]
Reopening, because I got one more question to @ribose-jeffreylau. How and when the `apiary.apib` is built? Should I run `make` in Travis before validating?

**Comment by ronaldtse** [comment]
@skalee the final file `apiary.apib` should be built whenever there is an update to the inner `apib` files. Perhaps we can add a Travis check to ensure that the `make update` is run, i.e., the git repo's `apiary.apib` is identical to the newly-generated one?

**Comment by skalee** [comment]
Thanks for clarification. Though personally, I think it's bit odd to keep the compilation result in source repository.

**Comment by skalee** [comment]
Fixed in #42.

**Comment by ronaldtse** [comment]
@skalee I agree that it's a weird process. The issue is that Apiary can only read a single file, and that single `apib` file is pulled from a git repo. Perhaps we can keep it this way for now...

**Comment by skalee** [comment]
I wonder… Since we got a makefile anyway, perhaps we should trigger validations in the makefile's default build step? I mean sth like:

```Makefile
default: validate

validate: apiary.abip
    # run validations

apiary.abip: input.apib $(DEPS)
    # build
```

**Comment by ronaldtse** [comment]
Sounds like a great idea @skalee !👍
