### ISSUE TITLE
Resource '/settings' is already defined validation error

### ISSUE THREAD

**Issue by skalee** [riboseinc/ribose-api#38]
Validator says:

```
warning code 2 in line 3197 - the resource '/settings' is already defined:
    ### Settings [/settings]
```

It's bit weird, and requires investigation. Problem *may* come from following document structure where we first define `/settings/general`, and then `/settings`, I don't know…

```markdown
## Group Settings
### General Settings [/settings/general]
### Settings [/settings]
```

**Comment by skalee** [comment]
Actually, there are two definitions of `GET /settings`. One by @kevinwongso introduced in 0e7a2600ed53146e5e2a489a0a4f0d4b61eb98df on Wed Nov 8, and another one by @ribose-jeffreylau in b8dfd050dc661198890d6282ba66f0bacfa3b15c on Tue Nov 7.

I'm going to keep the @kevinwongso's one as it's newer and more complete. The @ribose-jeffreylau's one is more like a documentation stub, and contains only:

```markdown
## Group General

### Request settings [GET /settings]

+ Request (application/json)

+ Response 200 (application/json)
```

**Comment by ribose-jeffreylau** [comment]
@skalee Yes, please go for it :)  Thanks!
